language: c
script: bash -e .travis-ci.sh
env:
  global:
    - OPAM_VERSION=1.1.0
  matrix:
    - OCAML_VERSION=4.02.0
    - OCAML_VERSION=4.01.0
    - OCAML_VERSION=4.00.1
    - OCAML_VERSION=3.12.1
matrix:
  allow_failures:
    - env: OCAML_VERSION=4.02.0
notifications:
  email:
    - opam-commits@lists.ocaml.org
  irc:
    - "chat.freenode.net#opam"
